### PR TITLE
Added SetAttributePrefix() function

### PR DESCRIPTION
**Pull request by xackery**
Without this, we are forced to always use the "-" prefix on attributes. Now, it can be set by calling the public function.

### CODE REVIEW

**Comment by basgys** [comment]
@xackery That's a good idea. However, this can't be global anymore, otherwise it would not be safe to use multiple instances of `Decoder` concurrently.

It would be better to have a custom `attrPrefix` as an attribute of `Decoder`, which would use the value of the global `attrPrefix` by default.

**Comment by xackery** [comment]
How does the above changes look? @basgys

**Comment by basgys** [comment]
That looks nice! 

Can you just remove the Makefile from this PR? Then we can merge it.

**Comment by xackery** [comment]
Done @basgys

**Pull request merged**
