### PR TITLE
Parsing JS types 

### PR DESCRIPTION
**Pull request by powerslacker**
Added test and logic for extracting js types of bool, int, and float -- updated README to reflect changes. Please review and advise if any further updates are needed for this to be feature complete.

### CODE REVIEW

**Comment by basgys** [comment]
Hi @powerslacker, 

First off, thank you! It's a great contribution. I just quickly reviewed the code and it looks good at first sight. We could improve/optimise the JS type detection, but it is not required.

You mentioned a potential problem when a field intended to be a string (e.g. phone number) is converted to a number. I am wondering if we should have a parameter to decide whether we want a type conversion or not. I would assume that some people are happy with strings and prefer to make a type conversion further up in their stack. Also, the update would be backward compatible.

What do you think?

**Comment by basgys** [comment]
Yes good idea! You can add the key prefix to these options.

**Comment by powerslacker** [comment]
Okay, the new commit has some changes to review. I've moved the JSON parsing logic into a `customSanitizer` plugin which can be initialized with `NewCustomSanitizer` and passing in the desired types. When calling the `Convert` function, the client can supply any number of `encoderPlugins`, which are added to the `Encoder`. This means `Encoder` behavior can be modified / extended without breaking backwards compatibility. 

The `customSanitizer` type should work for the vast majority of use cases, since it allows cherry picking the new parsing logic. Tests speak louder than words -- I've written a few to demonstrate the usage. 

Let me know what you think. I just saw the key prefix comment. I haven't used that functionality yet. Can you give me a brief overview so I can design a good plugin?

P.S. I've added myself to the contributor list in the readme so you won't have to when this PR is accepted.

**Comment by basgys** [comment]
That's a nice implementation! 

I just have an issue with the naming. What you've implemented is not really a sanitiser, but rather a type converter. The sanitisation process is just about making sure that a string won't make the JSON output invalid. I would be confused if I see "float sanitiser". This API would make more sense to me:

```go
json, err := xj.Convert(xml, xj.WithAttrPrefix("+"), xj.WithTypeConverter(xj.Float, xj.Number))
```

Also, we are now mixing UK and US spelling. :'(

**Attribute prefix**
XML can have nested tags and attributes with the same name. There are somehow two different namespaces.

```xml
<foo bar="one">
   <bar>two</bar>
</foo>

If you convert this to JSON, you would have:

```json
{
   "foo": {
      "bar": "one"
   }
}
```

That's why we need to prefix keys from attributes to avoid a name clash. I've added `-` by default, but some people wanted to use another prefix or no prefix at all.

We currently have a function "SetAttributePrefix", but we could remove it and use a functional option instead.

Kudos for the tests 🥇

**Comment by powerslacker** [comment]
Didn't even realize it was the UK spelling! I'll just go ahead with your naming scheme and add the plugin.

**Comment by basgys** [comment]
@powerslacker Many thanks for your contribution! Type conversion was on the TODO list for far too long.

**Pull request merged**
